import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const [applicationView, backend, service, windows, native, overlay, live, preload, livePreload, packager, styles] = await Promise.all([
  readFile(new URL("../desktop/src/ui.rs", import.meta.url), "utf8"),
  readFile(new URL("../desktop/backend/src/channel_ping.rs", import.meta.url), "utf8"),
  readFile(new URL("../desktop/backend/src/service.rs", import.meta.url), "utf8"),
  readFile(new URL("../desktop/backend/src/service_windows.rs", import.meta.url), "utf8"),
  readFile(new URL("../desktop/src/native.rs", import.meta.url), "utf8"),
  readFile(new URL("../channel-ping-overlay.html", import.meta.url), "utf8"),
  readFile(new URL("../channel-ping-live.html", import.meta.url), "utf8"),
  readFile(new URL("../service/channel-ping-overlay-preload.js", import.meta.url), "utf8"),
  readFile(new URL("../service/channel-ping-live-preload.js", import.meta.url), "utf8"),
  readFile(new URL("../scripts/package-dioxus.mjs", import.meta.url), "utf8"),
  readFile(new URL("../web/styles.css", import.meta.url), "utf8"),
])

test("고급 기능에서 실시간 게임 서버 모니터링을 켜고 끈다", () => {
  assert.match(applicationView, /h2 \{ "실시간 게임 서버 모니터링" \}/)
  assert.match(applicationView, /게임 중 현재 채널과 실제 연결 상태/)
  assert.match(applicationView, /이번 버전에서는 류트 서버의 채널만 확인 가능합니다\./)
  assert.match(applicationView, /application:set-channel-ping-setting/)
  assert.match(backend, /REMOTE_URL[\s\S]+channel\.csv/)
  assert.match(backend, /MEASURE_INTERVAL[\s\S]+from_secs\(60\)/)
  assert.match(backend, /WARMUP_MEASURE_INTERVAL[\s\S]+from_secs\(10\)/)
  assert.match(backend, /measurement_spacing\(count, self\.is_warming_up\(\)\)/)
  assert.match(backend, /SAMPLE_LIMIT:\s*usize = 20/)
  assert.match(backend, /median_us[\s\S]+variation_us[\s\S]+failure_percent/)
  assert.match(backend, /fn measure_next/)
  assert.doesNotMatch(backend, /std::thread::scope/)
  assert.match(backend, /FAILURE_SYNC_INTERVAL[\s\S]+60 \* 60/)
  assert.match(backend, /WH_KEYBOARD_LL/)
  assert.match(backend, /WH_MOUSE_LL/)
  assert.doesNotMatch(backend, /GetAsyncKeyState/)
  assert.match(service, /"channel-ping"[\s\S]+channel-ping-overlay[\s\S]+channel-ping-live/)
  assert.match(service, /prepare_channel_ping\(\)[\s\S]+InputMonitor::new\(\)/)
  assert.match(service, /let mut overlay_visible = false/)
  assert.match(service, /let mut live_visible = false/)
  assert.match(service, /sync_overlay_window\([\s\S]+channel_ping_id\(\)/)
  assert.match(backend, /GetExtendedTcpTable[\s\S]+GetPerTcpConnectionEStats/)
  assert.match(backend, /foreground_compact_target/)
  assert.match(backend, /foreground_is_windows_shell[\s\S]+startmenuexperiencehost\.exe/)
  assert.match(service, /expanded && foreground_is_shell/)
  assert.match(service, /Duration::from_secs\(1\)[\s\S]+refresh_active_connection/)
  assert.match(service, /\.poll\(expanded, &self\.env\)/)
  assert.match(service, /set_expanded\(true\)[\s\S]+show_channel_ping/)
  assert.match(service, /show_channel_ping_live/)
  assert.match(applicationView, /application:get-channel-ping-setting/)
})

test("실시간 점수 창은 초소형·전체 모드 모두 클릭 통과 topmost로 표시된다", () => {
  assert.match(windows, /"channel-ping-overlay"[\s\S]+transparent/)
  assert.match(windows, /"channel-ping-overlay"[\s\S]+width":584/)
  assert.match(windows, /"channel-ping-overlay"[\s\S]+height":400/)
  assert.match(windows, /"channel-ping-live"[\s\S]+width":420[\s\S]+height":30/)
  assert.match(backend, /overlay_bounds\(env, window, 584\.0, 400\.0, None\)/)
  assert.match(backend, /overlay_bounds\(env, window, 420\.0, 30\.0, Some\(12\.0\)\)/)
  assert.match(windows, /"channel-ping-overlay"[\s\S]+alwaysOnTop/)
  assert.match(windows, /ignoreMouseEvents/)
  assert.match(backend, /ShowWindowAsync/)
  assert.match(windows, /"opacity", json!\(1\)/)
  assert.match(windows, /physicalBounds/)
  assert.match(windows, /"showInactive"[\s\S]+rpc\.request/)
  assert.match(windows, /상단 실시간 핑 창/)
  assert.match(native, /"physicalBounds"/)
  assert.match(native, /"channel-ping-overlay\.html"/)
  assert.match(native, /"channel-ping-live\.html"/)
  assert.match(native, /"hwnd":window\.hwnd\(\) as usize/)
  assert.match(overlay, /채널 점수는 연결 시험 변동값을 기준으로 측정합니다/)
  assert.match(overlay, /실시간 점수 확인/)
  assert.doesNotMatch(overlay, /compact-status|body\.compact/)
  assert.match(overlay, /const channelGroups = \[\[1, 15\], \[16, 29\], \[30, 38\]\]/)
  assert.match(overlay, /if \(item\?\.endpoint\) group\.append/)
  assert.match(overlay, /grid-template-columns:\s*repeat\(3, 170px\)/)
  assert.match(overlay, /justify-content:\s*space-between/)
  assert.doesNotMatch(overlay, /0 18px 50px/)
  assert.match(overlay, /logo2-white-transparent\.png/)
  assert.match(overlay, /measurementSpanMs = status\.measurementSpanMs/)
  assert.match(overlay, /1분 미만 측정한 데이터입니다/)
  assert.match(overlay, /분간 측정한 데이터입니다/)
  assert.match(overlay, /activeConnection\?\.channel === item\.channel/)
  assert.match(overlay, /item\.variationScore/)
  assert.match(overlay, /item\.sampleCount < 3[\s\S]+측정 중/)
  assert.match(overlay, /: `\$\{score\}`/)
  assert.doesNotMatch(overlay, /`변동 \$\{/)
  assert.match(overlay, /sampleCount < 3[\s\S]+score <= 50[\s\S]+score <= 100[\s\S]+score <= 150/)
  assert.match(overlay, /variationGrade\(score, item\.sampleCount\)/)
  assert.match(overlay, /article\.current span::after[\s\S]+content: " 현재"/)
  assert.match(overlay, /article\.best\.good[\s\S]+article\.best\.normal[\s\S]+article\.best\.slow[\s\S]+article\.best\.critical/)
  assert.match(overlay, /score === bestScore/)
  assert.doesNotMatch(overlay, /article\.diagnostics/)
  assert.match(backend, /started\.elapsed\(\)\.as_micros\(\)/)
  assert.match(backend, /"peakVariationMs"/)
  assert.doesNotMatch(overlay, /item\.recommended/)
  assert.match(preload, /channel-ping:get-status/)
  assert.doesNotMatch(preload, /set|write|open/)
  assert.match(livePreload, /channel-ping:get-status/)
  assert.doesNotMatch(livePreload, /set|write|open/)
  assert.match(live, /width:\s*max-content/)
  assert.match(live, /#status\.stable[\s\S]+#status\.normal[\s\S]+#status\.unstable[\s\S]+#status\.failed/)
  assert.match(live, /activeConnection/)
  assert.match(live, /rttMs <= 10[\s\S]+rttMs <= 20[\s\S]+rttMs <= 30/)
  assert.match(live, /status\.hidden = !current \|\| current\.rttMs == null/)
  assert.match(live, /aria-live="polite" hidden/)
  assert.match(live, /현재[\s\S]+평균[\s\S]+averageRttMs[\s\S]+최대[\s\S]+maximumRttMs/)
  assert.match(live, /재전송[\s\S]+packetsRetransmitted/)
  assert.doesNotMatch(live, /\$\{current\.quality\}/)
  assert.match(backend, /ACTIVE_RTT_WINDOW[\s\S]+3 \* 60/)
  assert.match(backend, /sample_sum[\s\S]+score_denominator[\s\S]+variation_score/)
  assert.match(backend, /"averageRttMs": active\.average_rtt_ms/)
  assert.match(backend, /"maximumRttMs": active\.maximum_rtt_ms/)
  assert.match(backend, /"measurementSpanMs": measurement_span_ms/)
  assert.match(backend, /"packetsRetransmitted": active\.packets_retransmitted/)
  assert.match(windows, /channel_ping_live_visible[\s\S]+IsWindowVisible/)
  assert.match(windows, /hide_channel_ping_live[\s\S]+ShowWindowAsync[\s\S]+SW_HIDE/)
  assert.match(service, /live_visible \|\| self\.windows\.channel_ping_live_visible\(\)/)
  assert.match(packager, /channel-ping-overlay\.html/)
  assert.match(packager, /channel-ping-live\.html/)
  assert.match(packager, /channel\.csv/)
})

test("정지 화면의 터보키 제거 버튼은 문구 양옆 여백을 유지한다", () => {
  assert.match(styles, /button\.turbo-key-remove\s*\{[\s\S]*min-width:\s*72px/)
  assert.match(styles, /button\.turbo-key-remove\s*\{[\s\S]*padding:\s*0 5px/)
})
